### ISSUE TITLE
Clase 01 Python videos 1, 2, 3.

### ISSUE THREAD

**Issue by DanielGuerrero03** [CodeSystem2022/Cuarto-Semestre-Grupo-Bestias-Binarias#1]
crear archivo UML , subir capturas de la creacion de tabla, crear archivo usuario.py

**Comment by FlorenciaOrtega82** [comment]
Creación de archivo usuario, creación de carpeta de capturas de base de datos.
Creación de archivo UML.

**Comment by DanielGuerrero03** [comment]
Perfecto muchas gracias!
