### ISSUE TITLE
Clase 01 e-commerce (JavaScript) video 1 y 2

### ISSUE THREAD

**Issue by DanielGuerrero03** [CodeSystem2022/Cuarto-Semestre-Grupo-Bestias-Binarias#4]
Crear Archivos index.html e index.js con todo su contenido debera ver videos 3 y 4 para que no falte nada, todo en sus respectivas carpetas

**Comment by FernandoSilva12** [comment]
Ahi se completo la asistencia dani, abrazo grande!!

**Comment by DanielGuerrero03** [comment]
Perfecto muchas gracias!
