### ISSUE TITLE
Clase 01 e-commerce (JavaScript) video 3 y 4

### ISSUE THREAD

**Issue by DanielGuerrero03** [CodeSystem2022/Cuarto-Semestre-Grupo-Bestias-Binarias#5]
Crear Archivos Css necesarios e product.js con todo su contenido debera ver videos 1 y 2 para que no falte nada, todo en sus respectivas carpetas

**Comment by gabrielromero0** [comment]
Finalizado!

**Comment by DanielGuerrero03** [comment]
Perfecto muchas gracias!
