### ISSUE TITLE
Python Clase 5 Videos 1 y 2

### ISSUE THREAD

**Issue by FernandoSilva12** [CodeSystem2022/Cuarto-Semestre-Grupo-Bestias-Binarias#54]
Buenas Dai , esta semana toco videos 1y2  de la clase 5 de py abrazooo

**Comment by DaianaEscudero** [comment]
Fer buenas noches, ya realicé la tarea asignada de ésta semana!!!

**Comment by FernandoSilva12** [comment]
Perfecto dai, abrazoo
